security:
    providers:
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
#        api:
#            pattern: ^/api/(?!(login)).*$
#            stateless: true

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
